"""Added database

Revision ID: 6a4d853aabce
Revises: 8f58cd776eda
Create Date: 2020-12-23 13:49:00.640607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4d853aabce'
down_revision = '8f58cd776eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
