"""Added Device.file_server_address

Revision ID: 6d5c250f098c
Revises: fb245977373f
Create Date: 2021-01-26 14:55:11.504148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5c250f098c'
down_revision = 'fb245977373f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('file_server_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'file_server_address')
    # ### end Alembic commands ###
