"""Added database

Revision ID: 8f58cd776eda
Revises: 
Create Date: 2020-12-23 13:38:47.314749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f58cd776eda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistic',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('statistic_type', sa.Enum('REPORT', 'ALERT', name='statistictypeenum'), nullable=True),
    sa.Column('people_with_mask', sa.Integer(), nullable=True),
    sa.Column('people_without_mask', sa.Integer(), nullable=True),
    sa.Column('people_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'datetime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    op.drop_table('device')
    # ### end Alembic commands ###
